# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
# patch_file = "src/schema.patch"
with_docs = false

[migrations_directory]
dir = "migrations"
